color_circle: black
review_star: 1

platformName: "Android"
appium:deviceName: "emulator-5554"
appium:appPackage: "com.saucelabs.mydemoapp.rn"
appium:appActivity: "com.saucelabs.mydemoapp.rn.MainActivity"
appium:automationName: "UiAutomator2"
appium:uiautomator2ServerInstallTimeout: "60000"
appium:noReset: True
appium:ensureWebviewsHavePages: True
appium:disableWindowAnimation: True
appium:newCommandTimeout: 300
appium:app: "/Users/javhierralejandro/Downloads/Android-MyDemoAppRN.1.3.0.build-244.apk"